# Generated by Django 4.2.4 on 2023-08-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gooritouser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gooritouser',
            options={},
        ),
        migrations.AlterModelTable(
            name='gooritouser',
            table='gooritouser',
        ),
        migrations.AlterModelTable(
            name='preference',
            table='preference',
        ),
    ]
