# Generated by Django 4.2.4 on 2023-09-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gooritouser', '0003_gooritouser_gender_alter_gooritouser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gooritouser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='gooritouser',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='gooritouser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='gooritouser',
            name='lifestyle_preferences',
        ),
        migrations.RemoveField(
            model_name='gooritouser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='gooritouser',
            name='profile_image',
        ),
    ]
