# Generated by Django 4.2.4 on 2023-09-08 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gooritouser', '0004_remove_gooritouser_bio_remove_gooritouser_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooritoUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(null=True)),
                ('location', models.CharField(max_length=250, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('lifestyle_preferences', models.ManyToManyField(to='gooritouser.preference')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
