# Generated by Django 4.2.4 on 2023-09-08 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gooritouser', '0005_gooritouserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gooritouserprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='gooritouser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gooritouser.gooritouserprofile'),
        ),
    ]
