# Generated by Django 4.2.4 on 2023-09-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apartment',
            table='apartment',
        ),
    ]
